export const data = [
  {
    id: 1,
    title: "HomeWorks",
    subtitle: "Progress & details of homework",
    image: require("./assets/images/Homework.png"),
  },
  {
    id: 2,
    title: "Timetable",
    subtitle: "Progress & details of homework",
    image: require("./assets/images/Timetable.png"),
  },
  {
    id: 3,
    title: "Exams",
    subtitle: "Reports / results of exams",
    image: require("./assets/images/Exams.png"),
  },
  {
    id: 4,
    title: "Fee",
    subtitle: "View past & upcoming dues",
    image: require("./assets/images/Fee.png"),
  },
];
export const AllSubjects = [
  {
    id: 1,
    subject: "Maths",
    subjectImage: require("./assets/images/Math.png"),
    TeacherImage: require("./assets/images/sofia.png"),
    TeacherName: "Sofia",
    subjectTeacher: "Math Teacher",
    PeriodNumber: "Period 01",
    PeriodTime: "08:00 AM - 09:00 AM",
  },
  {
    id: 2,
    subject: "Physics",
    subjectImage: require("./assets/images/Physics.png"),
    TeacherImage: require("./assets/images/amina.png"),
    TeacherName: "Amina",
    subjectTeacher: "Physics Teacher",
    PeriodNumber: "Period 02",
    PeriodTime: "08:00 AM - 09:00 AM",
  },
  {
    id: 3,
    subject: "Chemistry",
    subjectImage: require("./assets/images/Chemistry.png"),
    TeacherImage: require("./assets/images/ahmed.png"),
    TeacherName: "Ahmed",
    subjectTeacher: "Chemistry Teacher",
    PeriodNumber: "Period 03",
    PeriodTime: "08:00 AM - 09:00 AM",
  },
  {
    id: 4,
    subject: "Biology",
    subjectImage: require("./assets/images/biology.png"),
    TeacherImage: require("./assets/images/munir.png"),
    TeacherName: "Munir",
    subjectTeacher: "Biology Teacher",
    PeriodNumber: "Period 04",
    PeriodTime: "08:00 AM - 09:00 AM",
  },
  {
    id: 5,
    subject: "Arabic",
    subjectImage: require("./assets/images/Arabic.png"),
    TeacherImage: require("./assets/images/shakir.png"),
    TeacherName: "Shakir",
    subjectTeacher: "Arabic Teacher",
    PeriodNumber: "Period 05",
    PeriodTime: "08:00 AM - 09:00 AM",
  },
];
